;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        handle-switch-frame
        keyboard-escape-quit
        mouse-wheel-text-scale
        ))

(setq mc/cmds-to-run-once
      '(
        lsp-ui-doc--handle-mouse-movement
        ))
