;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        handle-switch-frame
        ignore-preserving-kill-region
        treemacs-leftclick-action
        ))

(setq mc/cmds-to-run-once
      '(
        lsp-ui-doc--handle-mouse-movement
        mouse-set-region
        ))
