;;; wgsl-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wgsl-mode.el

(autoload 'wgsl-mode "wgsl-mode" "\
Major mode for WGSL source.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.wgsl\\'" . wgsl-mode))
(register-definition-prefixes "wgsl-mode" '("wgsl-"))

;;; End of scraped data

(provide 'wgsl-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wgsl-mode-autoloads.el ends here
